USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE MYDB;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::470957633639:role/realtime-snowflakerole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://dea-realtimeprojectdata/data/');


    DESC INTEGRATION S3_INT;

CREATE OR REPLACE STAGE MYDB.PUBLIC.S3_STAGE
STORAGE_INTEGRATION = S3_INT
URL= 's3://dea-realtimeprojectdata/data/';

    ls @MYDB.PUBLIC.S3_STAGE;

CREATE OR REPLACE TABLE MYDB.PUBLIC.MYTABLE
(
DATA VARIANT
);

CREATE OR REPLACE PIPE MYDB.PUBLIC.MYPIPE AUTO_INGEST = TRUE AS
COPY INTO MYDB.PUBLIC.MYTABLE
FROM @MYDB.PUBLIC.S3_STAGE
FILE_FORMAT = (TYPE = 'JSON');

    USE SCHEMA MYDB.PUBLIC;
    SHOW PIPES;